export const products = [
  {
    id: 1,
    name: "Milanesas de Pollo Rebozadas",
    subtitle: "Preparadas artesanalmente",
    description: "Milanesas tiernas listas para cocinar.",
    price: 1200,
    offer: { quantity: "2 kg", price: 2100 },
    category: "milanesas",
    image: "",
  },
  {
    id: 2,
    name: "Milanesas de Carne Vacuna",
    subtitle: "Corte premium",
    description: "Milanesas elaboradas con nalga seleccionada.",
    price: 1500,
    offer: { quantity: "2 kg", price: 2700 },
    category: "milanesas",
    image: "/images/milanesa-carne.jpg",
  },
  {
    id: 3,
    name: "Milanesas Napolitanas",
    subtitle: "Lista para horno",
    description: "Con salsa, jamón y queso.",
    price: 1800,
    offer: null,
    category: "milanesas",
    image: "/images/milanesa-napo.jpg",
  },
  {
    id: 4,
    name: "Hamburguesas Clásicas",
    subtitle: "4 unidades",
    description: "Blend de carne vacuna seleccionada.",
    price: 1800,
    offer: { quantity: "2 packs", price: 3200 },
    category: "hamburguesas",
    image: "/images/hamburguesa-clasica.jpg",
  },
  {
    id: 5,
    name: "Hamburguesas Premium",
    subtitle: "4 Pack - Premium Blend",
    description: "Jugosas y con el equilibrio perfecto de grasa.",
    price: 2200,
    offer: { quantity: "2 packs", price: 3900 },
    category: "hamburguesas",
    image: "/images/hamburguesa-premium.jpg",
  },
  {
    id: 6,
    name: "Hamburguesas de Pollo",
    subtitle: "4 unidades",
    description: "Suaves y sabrosas para toda la familia.",
    price: 1600,
    offer: null,
    category: "hamburguesas",
    image: "/images/hamburguesa-pollo.jpg",
  },
  {
    id: 7,
    name: "Pechuga de Pollo",
    subtitle: "Sin hueso",
    description: "Ideal para milanesas o a la plancha.",
    price: 1900,
    offer: { quantity: "2 kg", price: 3500 },
    category: "pollo",
    image: "/images/pechuga.jpg",
  },
  {
    id: 8,
    name: "Suprema de Pollo",
    subtitle: "Fresca del día",
    description: "Corte premium de pollo.",
    price: 2100,
    offer: null,
    category: "pollo",
    image: "/images/suprema.jpg",
  },
  {
    id: 9,
    name: "Patitas de Pollo",
    subtitle: "Rebozadas",
    description: "Perfectas para los más chicos.",
    price: 1700,
    offer: { quantity: "2 bolsas", price: 3000 },
    category: "pollo",
    image: "/images/patitas.jpg",
  },
  {
    id: 10,
    name: "Alitas Marinadas",
    subtitle: "Listas para horno",
    description: "Marinadas con especias caseras.",
    price: 1800,
    offer: null,
    category: "pollo",
    image: "/images/alitas.jpg",
  },
  {
    id: 11,
    name: "Carne Picada Especial",
    subtitle: "100% vacuna",
    description: "Ideal para hamburguesas y albóndigas.",
    price: 1400,
    offer: { quantity: "2 kg", price: 2500 },
    category: "carne",
    image: "/images/picada.jpg",
  },
  {
    id: 12,
    name: "Bife de Chorizo",
    subtitle: "Corte premium",
    description: "Tierno y jugoso para la parrilla.",
    price: 2800,
    offer: null,
    category: "carne",
    image: "/images/bife.jpg",
  },
  {
    id: 13,
    name: "Vacío",
    subtitle: "Especial parrilla",
    description: "Uno de los cortes favoritos de los argentinos.",
    price: 2600,
    offer: { quantity: "2 kg", price: 4700 },
    category: "carne",
    image: "/images/vacio.jpg",
  },
  {
    id: 14,
    name: "Asado de Tira",
    subtitle: "Corte tradicional",
    description: "Perfecto para reuniones familiares.",
    price: 2500,
    offer: null,
    category: "carne",
    image: "/images/asado.jpg",
  },
  {
    id: 15,
    name: "Chorizo Criollo",
    subtitle: "Receta tradicional",
    description: "Ideal para parrilla o choripanes.",
    price: 1900,
    offer: { quantity: "2 kg", price: 3400 },
    category: "chorizos",
    image: "/images/chorizo.jpg",
  },
  {
    id: 16,
    name: "Chorizo Bombón",
    subtitle: "Tamaño cocktail",
    description: "Perfecto para picadas y eventos.",
    price: 2100,
    offer: null,
    category: "chorizos",
    image: "/images/chorizo-bombon.jpg",
  },
  {
    id: 17,
    name: "Chorizo Especial",
    subtitle: "Con especias seleccionadas",
    description: "Sabor intenso y artesanal.",
    price: 2200,
    offer: { quantity: "2 kg", price: 4000 },
    category: "chorizos",
    image: "/images/chorizo-especial.jpg",
  },
  {
    id: 18,
    name: "Combo Parrillero",
    subtitle: "Para 4 personas",
    description: "Asado, chorizos y morcillas.",
    price: 8500,
    offer: { quantity: "Promo", price: 7500 },
    category: "combos",
    image: "/images/combo-parrilla.jpg",
  },
  {
    id: 19,
    name: "Combo Hamburguesero",
    subtitle: "Ideal para reuniones",
    description: "12 hamburguesas + panes.",
    price: 7200,
    offer: { quantity: "Promo", price: 6500 },
    category: "combos",
    image: "/images/combo-burger.jpg",
  },
  {
    id: 20,
    name: "Combo Familiar",
    subtitle: "Variedad para toda la familia",
    description: "Pollo, milanesas y hamburguesas.",
    price: 9800,
    offer: { quantity: "Promo", price: 8900 },
    category: "combos",
    image: "/images/combo-familiar.jpg",
  },
];